[package]
name = "tree"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
schema = ["dep:sdk"]
testing = []

[dependencies]
sdk = { workspace = true, optional = true, features = ["schema"] }

serde = { workspace = true, features = ["std", "derive"] }

[dev-dependencies]
serde-json-wasm = { workspace = true }
