name: "Setup environment"
description: "Action for setting up environment for smart contracts"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  build_wasm:
    description: "Whether the build is targeting WebAssembly binaries."
    required: false
  target_net:
    description: 'Whether to build targeting dev-net, test-net or main-net. This parameter takes one of these values: "dev", "test" and "main".'
    required: false
  target_protocol:
    description: "Indicates which protocol the build targets."
    required: false
  protocols_list:
    description: "Contains a list of all protocols."
    required: false

outputs:
  features:
    description: "Features to be turned on during compilation."
    value: "${{ steps.env.outputs.features }}"
  exclude_features:
    description: "Features to be turned off during compilation with mixed features."
    value: "${{ steps.env.outputs.exclude_features }}"

runs:
  using: composite
  steps:
    - id: "env"
      shell: "bash"
      run: |
        if ! test '${{ inputs.build_wasm }}' = ''
        then
          FEATURES='contract'
        else
          FEATURES=''
        fi

        exclude_features=''

        if ! test '${{ inputs.target_net }}' = ''
        then
          FEATURES="net_${{ inputs.target_net }},${FEATURES}"

          networks='net_dev,net_test,net_main'

          exclude_features="${exclude_features},${networks//net_${{ inputs.target_net }}/}"

          echo 'dash_net_name=-${{ inputs.target_net }}' >> "${GITHUB_ENV}"
        fi

        if ! test '${{ inputs.target_protocol }}' = ''
        then
          target_protocol='${{ inputs.target_protocol }}'

          FEATURES="${{ inputs.target_protocol }},${FEATURES}"

          protocols='${{ inputs.protocols_list }}'

          exclude_features="${exclude_features},${protocols//${target_protocol}/}"

          echo 'dash_protocol_name=-${{ inputs.target_protocol }}' >> "${GITHUB_ENV}"
        fi

        echo "FEATURES=${FEATURES}" >> "${GITHUB_ENV}"

        echo "features=${FEATURES}" >> "${GITHUB_OUTPUT}"

        echo "exclude_features=${exclude_features}" >> "${GITHUB_OUTPUT}"
