name: "Linting"
description: "Action for linting"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  rust-version:
    description: ""
    required: true
  working-directory:
    description: ""
    required: true
  network:
    description: ""
    required: true
  protocol:
    description: ""
    required: true
  profile:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: "Restore Rust toolchain and dependencies"
      uses: "./.github/actions/cache-rust"
      with:
        cache-cargo: "true"
        working-directory: |-
          ${{ inputs.working-directory }}
        cache-rust-stable: "true"
        rust-stable: |-
          ${{ inputs.rust-version }}
        cache-rust-nightly: "false"
        no-fetching: "false"
        fail-on-cache-miss: "true"
    - name: "Restore \"cargo-each\""
      uses: "./.github/actions/install-tool"
      with:
        no-fetching: "false"
        fail-on-cache-miss: "true"
        tool: "cargo-each"
        local: "true"
        rust-version: |-
          ${{ inputs.rust-version }}
    - name: 'Run linter'
      shell: "sh"
      env:
        rust_version: |-
          ${{ inputs.rust-version }}
        working_directory: |-
          ${{ inputs.working-directory }}
        network: |-
          ${{ inputs.network }}
        protocol: |-
          ${{ inputs.protocol }}
        profile: |-
          ${{ inputs.profile }}
      run: |
        cargo "+${rust_version}" -- each run --external-command \
          --print-command --github-actions-logging --tag ci --tag "${network}" \
          --tag "${protocol}" -- ../lint.sh --profile "${profile}" \
          --not-as-workspace
      working-directory: |-
        ${{ inputs.working-directory }}
