[package]
name = "versioning"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "@agnostic"], include-rest = true }
]

[features]
schema = ["sdk/schema"]

[dependencies]
sdk = { workspace = true, features = ["cosmos", "schema", "storage"] }

serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1"
