[package]
name = "profit"
version = "0.6.4"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["build", "$net", "$protocol"], always-on = ["contract", "$net", "$protocol"], include-rest = false, generics = { "$net" = "net", "$protocol" = "protocol" } },
    { tags = ["build", "net_main", "neutron-astroport-usdc_noble"], always-on = ["net_main", "neutron-astroport-usdc_noble"], include-rest = false },
    { tags = ["build", "net_main", "osmosis-osmosis-statom"], always-on = ["net_main", "osmosis-osmosis-statom"], include-rest = false },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["net", "protocol", "contract-or-stub", "testing"], always-on = ["$net", "$protocol"], include-rest = false, generics = { "$net" = "net", "$protocol" = "protocol" } },
    { tags = ["ci", "net_main", "neutron-astroport-usdc_noble"], feature-groups = ["testing"], always-on = ["net_main", "neutron-astroport-usdc_noble"], include-rest = false },
    { tags = ["ci", "net_main", "osmosis-osmosis-statom"], feature-groups = ["testing"], always-on = ["net_main", "osmosis-osmosis-statom"], include-rest = false }
]
feature-groups = { net = { members = ["net_dev", "net_test", "net_main"], at-least-one = true, mutually-exclusive = true }, protocol = { members = ["neutron-astroport-usdc_axelar", "osmosis-osmosis-usdc_axelar", "osmosis-osmosis-usdc_noble"], at-least-one = true, mutually-exclusive = true }, contract-or-stub = { members = ["contract", "stub"], at-least-one = false, mutually-exclusive = true }, testing = { members = ["testing"], at-least-one = false, mutually-exclusive = false } }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
net_dev = ["dep:swap", "contract", "swap/test"]
net_test = ["dep:swap", "contract", "swap/test"]
net_main = ["dep:swap", "contract", "swap/main"]

neutron-astroport-usdc_axelar = ["contract", "swap/astroport"]
neutron-astroport-usdc_noble = ["contract", "swap/astroport"]
osmosis-osmosis-statom = ["contract", "swap/osmosis"]
osmosis-osmosis-usdc_axelar = ["contract", "swap/osmosis"]
osmosis-osmosis-usdc_noble = ["contract", "swap/osmosis"]

contract = [
    "sdk/contract",
    "dep:access-control",
    "dep:cosmwasm-std",
    "dep:currencies",
    "dep:currency",
    "dex/impl",
    "dep:finance",
    "dep:oracle",
    "dep:oracle-platform",
    "dep:platform",
    "dep:timealarms",
    "dep:thiserror",
    "dep:versioning",
]
stub = ["dep:platform", "dep:thiserror"]
testing = []

[dependencies]
access-control = { workspace = true, optional = true }
currencies = { workspace = true, optional = true }
currency = { workspace = true, optional = true }
dex = { workspace = true }
finance = { workspace = true, optional = true }
oracle = { workspace = true, optional = true }
oracle-platform = { workspace = true, optional = true }
platform = { workspace = true, optional = true }
sdk = { workspace = true }
swap = { workspace = true, optional = true }
timealarms = { workspace = true, optional = true, features = ["stub"] }
versioning = { workspace = true, optional = true }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true, optional = true }

thiserror = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currencies = { workspace = true, features = ["testing"] }
currency = { workspace = true, features = ["testing"] }
dex = { workspace = true, features = ["testing"] }
finance = { workspace = true }
oracle = { workspace = true, features = ["testing"] }
oracle-platform = { workspace = true, features = ["testing"] }
timealarms = { workspace = true, features = ["testing"] }
schema = { workspace = true }
swap = { workspace = true, features = ["testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { workspace = true, features = ["testing"] }
