[package]
name = "profit"
version = "0.5.7"
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
net_dev = ["dex/net_dev"]
net_test = ["dex/net_test"]
net_main = ["dex/net_main"]

astroport = ["api", "dex/astroport"]
osmosis = ["api", "dex/osmosis"]

cosmwasm-bindings = []
api = []
stub = ["api"]
testing = []

[dependencies]
access-control = { workspace = true }
currencies = { workspace = true }
currency = { workspace = true }
dex = { workspace = true, optional = true }
finance = { workspace = true }
oracle-platform = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true, features = ["contract"] }
timealarms = { workspace = true, features = ["stub"] }
versioning = { workspace = true }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currencies = { workspace = true, features = ["testing"] }
currency = { workspace = true, features = ["testing"] }
dex = { workspace = true, features = ["testing"] }
finance = { workspace = true }
oracle-platform = { workspace = true, features = ["testing"] }
timealarms = { workspace = true, features = ["testing"] }
schema = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { workspace = true, features = ["testing"] }
