[package]
name = "currencies"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "$net", "$protocol"], include-rest = true, generics = { "$net" = ["net_dev", "net_test", "net_main"], "$protocol" = ["neutron-astroport-usdc_axelar", "osmosis-osmosis-usdc_axelar", "osmosis-osmosis-usdc_noble"] } },
    { tags = ["ci", "net_main", "neutron-astroport-usdc_noble"], include-rest = true }
]

[lib]
doctest = false

[features]
testing = []

[dependencies]
currency = { workspace = true }
sdk = { workspace = true, features = ["schema"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
