[package]
name = "lease"
version = "0.8.5"
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
net_dev = ["contract", "dex/net_dev"]
net_test = ["contract", "dex/net_test"]
net_main = ["contract", "dex/net_main"]

astroport = ["contract", "dex/astroport", "dex/migration"]
osmosis = ["contract", "dex/osmosis", "dex/migration"]

contract = [
    "skel",
    "sdk/contract",
    "dep:cosmwasm-std",
    "dep:enum_dispatch",
    "dep:marketprice",
    "dep:versioning",
]
skel = [
    "dep:access-control",
    "dep:dex",
    "dep:lpp",
    "dep:oracle",
    "dep:oracle-platform",
    "dep:platform",
    "dep:profit",
    "dep:timealarms",
    "dep:thiserror",
]
testing = ["currencies/testing", "currency/testing", "finance/testing"]

[dependencies]
access-control = { workspace = true, optional = true }
profit = { workspace = true, optional = true, features = ["stub"] }
timealarms = { workspace = true, optional = true, features = ["stub"] }

currencies = { workspace = true }
currency = { workspace = true }
dex = { workspace = true, optional = true }
finance = { workspace = true }
lpp = { workspace = true, optional = true, features = ["stub"] }
lpp-platform = { workspace = true, optional = true }
marketprice = { workspace = true, optional = true }
oracle = { workspace = true, optional = true, features = ["stub"] }
oracle-platform = { workspace = true, optional = true }
platform = { workspace = true, optional = true }
sdk = { workspace = true }
versioning = { workspace = true, optional = true }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true, optional = true }

enum_dispatch = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
timealarms = { workspace = true, features = ["testing"] }
lpp = { workspace = true, features = ["testing"] }
profit = { workspace = true, features = ["testing"] }
oracle = { workspace = true, features = ["testing"] }
oracle-platform = { workspace = true, features = ["testing"] }
finance = { workspace = true, features = ["testing"] }
currencies = { workspace = true, features = ["testing"] }
currency = { workspace = true, features = ["testing"] }
marketprice = { workspace = true, features = ["testing"] }
platform = { workspace = true, features = ["testing"] }
schema = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { workspace = true, features = ["testing"] }
