name: "Unused dependencies"
description: "Action for checking for unused dependencies"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  stable-rust-version:
    description: ""
    required: true
  nightly-rust-version:
    description: ""
    required: true
  working-directory:
    description: ""
    required: true
  network:
    description: ""
    required: true
  protocol:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: "Restore Rust toolchain and dependencies"
      uses: "./.github/actions/cache-rust"
      with:
        cache-cargo: "true"
        working-directory: |-
          ${{ inputs.working-directory }}
        cache-rust-stable: "false"
        rust-stable: |-
          ${{ inputs.stable-rust-version }}
        cache-rust-nightly: "true"
        rust-nightly: |-
          ${{ inputs.nightly-rust-version }}
        no-fetching: "false"
        fail-on-cache-miss: "true"
    - name: "Restore \"cargo-each\""
      uses: "./.github/actions/install-tool"
      with:
        no-fetching: "false"
        fail-on-cache-miss: "true"
        tool: "cargo-each"
        local: "true"
        rust-version: |-
          ${{ inputs.stable-rust-version }}
    - name: "Restore \"cargo-udeps\""
      uses: "./.github/actions/install-tool"
      with:
        no-fetching: "false"
        fail-on-cache-miss: "true"
        tool: "cargo-udeps"
        local: "false"
    - name: "Check for unused dependencies"
      shell: "sh"
      env:
        rust_version: |-
          ${{ inputs.nightly-rust-version }}
        network: |-
          ${{ inputs.network }}
        protocol: |-
          ${{ inputs.protocol }}
      run: |
        cargo "+${rust_version}" -- each run --print-command \
          --github-actions-logging --tag ci --tag "${network}" \
          --tag "${protocol}" -- udeps --all-targets
      working-directory: |-
        ${{ inputs.working-directory }}
