[package]
name = "dex"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
impl = []
migration = []
testing = []

[dependencies]
currency = { workspace = true }
finance = { workspace = true }
oracle = { workspace = true, features = ["stub_swap"] }
oracle-platform = { workspace = true }
timealarms = { workspace = true, features = ["stub"] }
platform = { workspace = true }
sdk = { workspace = true, features = ["schema"] }

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
