[package]
name = "reserve"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = [
        "build",
        "$net",
        "$protocol",
    ], always-on = [
        "contract",
        "$net",
        "$protocol",
    ], include-rest = false, generics = { "$net" = "net", "$protocol" = "protocol" } },
    { tags = [
        "build",
        "net_main",
        "neutron-astroport-usdc_noble",
    ], always-on = [
        "net_main",
        "neutron-astroport-usdc_noble",
    ], include-rest = false },
    { tags = [
        "ci",
        "$net",
        "$protocol",
    ], feature-groups = [
        "net",
        "protocol",
        "contract-or-stub",
        "testing",
    ], always-on = [
        "$net",
        "$protocol",
    ], include-rest = false, generics = { "$net" = "net", "$protocol" = "protocol" } },
    { tags = [
        "ci",
        "net_main",
        "neutron-astroport-usdc_noble",
    ], feature-groups = [
        "testing",
    ], always-on = [
        "net_main",
        "neutron-astroport-usdc_noble",
    ], include-rest = false },
    { tags = [
        "ci",
        "net_main",
        "osmosis-osmosis-statom",
    ], feature-groups = [
        "testing",
    ], always-on = [
        "net_main",
        "osmosis-osmosis-statom",
    ], include-rest = false },
]
# TODO add "stub" when feature is added
feature-groups = { net = { members = [
    "net_dev",
    "net_test",
    "net_main",
], at-least-one = true, mutually-exclusive = true }, protocol = { members = [
    "neutron-astroport-usdc_axelar",
    "osmosis-osmosis-usdc_axelar",
    "osmosis-osmosis-usdc_noble",
], at-least-one = true, mutually-exclusive = true }, contract-or-stub = { members = [
    "contract",
], at-least-one = false, mutually-exclusive = true }, testing = { members = [
    "testing",
], at-least-one = false, mutually-exclusive = false } }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
net_dev = ["contract"]
net_test = ["contract"]
net_main = ["contract"]

neutron-astroport-usdc_axelar = ["contract"]
neutron-astroport-usdc_noble = ["contract"]
osmosis-osmosis-statom = ["contract"]
osmosis-osmosis-usdc_axelar = ["contract"]
osmosis-osmosis-usdc_noble = ["contract"]

contract = ["stub", "sdk/contract", "dep:cosmwasm-std", "dep:versioning"]
stub = ["dep:thiserror"]
testing = []

[dependencies]
access-control = { workspace = true }
currencies = { workspace = true }
currency = { workspace = true }
finance = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true }
versioning = { workspace = true, optional = true }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true, optional = true }

thiserror = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currencies = { workspace = true, features = ["testing"] }
platform = { workspace = true, features = ["testing"] }
schema = { workspace = true }
sdk = { workspace = true, features = ["testing"] }
