[package]
name = "access-control"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdk = { workspace = true, features = ["cosmos", "storage"] }
thiserror = { workspace = true }

[dev-dependencies]
sdk = { workspace = true, features = ["cosmos", "storage", "testing"] }
