[package]
name = "marketprice"
version = "0.3.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
astroport = ["currencies/astroport"]
osmosis = ["currencies/osmosis"]

testing = []

[dependencies]
# TODO get rid of this dependency
currencies = { workspace = true }
currency = { workspace = true }
finance = { workspace = true }
sdk = { workspace = true, features = ["storage", "schema"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
postcard = { workspace = true, features = ["alloc"] }

[dev-dependencies]
currencies = { workspace = true, features = ["testing"] }
finance = { workspace = true, features = ["testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { workspace = true, features = ["testing"] }
