[package]
name = "oracle"
version = "0.5.10"
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
net_dev = ["contract", "currencies/net_dev"]
net_test = ["contract", "currencies/net_test"]
net_main = ["contract", "currencies/net_main"]

astroport = ["contract", "currencies/astroport"]
osmosis = ["contract", "currencies/osmosis"]

contract = [
    "stub",
    "sdk/contract",
    "dep:cosmwasm-std",
    "dep:currencies",
    "dep:versioning",
]
testing = ["stub", "marketprice/testing"]
stub = ["dep:oracle-platform"]

[dependencies]
currencies = { workspace = true, optional = true }
currency = { workspace = true }
finance = { workspace = true }
marketprice = { workspace = true }
oracle-platform = { workspace = true, optional = true }
platform = { workspace = true }
sdk = { workspace = true }
swap = { workspace = true }
tree = { workspace = true, features = ["schema"] }
versioning = { workspace = true, optional = true, features = ["schema"] }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true, optional = true }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currencies = { workspace = true, features = ["testing"] }
currency = { workspace = true, features = ["testing"] }
finance = { workspace = true }
platform = { workspace = true, features = ["testing"] }
schema = { workspace = true }
marketprice = { workspace = true, features = ["testing"] }
tree = { workspace = true, features = ["schema", "testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { workspace = true, features = ["testing"] }
