[package]
name = "void"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "@agnostic"], include-rest = true }
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
platform = { workspace = true }
sdk = { workspace = true }
timealarms = { workspace = true }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true }

serde = { workspace = true, features = ["derive"] }
