[package]
name = "swap"
version = "0.1.1"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
astroport = [
    "sdk/cosmos_ibc",
    "dep:astroport",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
]
osmosis = [
    "sdk/cosmos",
    "dep:osmosis-std",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
]

testing = ["dex/testing"]

[dependencies]
currency = { workspace = true, optional = true }
dex = { workspace = true, optional = true }
finance = { workspace = true, optional = true }
oracle = { workspace = true, features = ["stub_swap"], optional = true }
platform = { workspace = true, optional = true }
sdk = { workspace = true, features = ["schema"], optional = true }

astroport = { workspace = true, optional = true }
osmosis-std = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
dex = { workspace = true, features = ["testing"] }
