[package]
name = "swap"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
trx = ["sdk/cosmos", "dep:osmosis-std"]
testing = []

[dependencies]
currency = { workspace = true }
finance = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true, features = ["schema"] }

osmosis-std = { workspace = true, optional = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }