[package]
name = "swap"
version = "0.1.1"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "net_dev", "net_test", "net_main", "neutron-astroport-usdc_axelar"], feature-groups = ["dex", "astroport-net"], always-on = ["astroport"], include-rest = true },
    { tags = ["ci", "net_main", "neutron-astroport-usdc_noble"], feature-groups = ["testing"], always-on = ["main", "astroport"], include-rest = false },
    { tags = ["ci", "net_dev", "net_test", "net_main", "osmosis-osmosis-statom", "osmosis-osmosis-usdc_axelar", "osmosis-osmosis-usdc_noble"], feature-groups = ["dex", "osmosis-and-astroport-net"], always-on = ["osmosis"], include-rest = true }
]
feature-groups = { astroport-net = { members = ["test", "main"], at-least-one = true, mutually-exclusive = true }, dex = { members = ["astroport", "osmosis"], at-least-one = true, mutually-exclusive = true }, osmosis-and-astroport-net = { members = ["osmosis", "test", "main"], at-least-one = true, mutually-exclusive = true }, testing = { members = ["testing"], at-least-one = false, mutually-exclusive = false } }

[features]
# TODO get rid of main and test and specialize astroport into ~_main and ~_test when the CI builds protocols provided as input
# instead of implicitly building them in matrix
main = []
test = []

astroport = [
    "sdk/cosmos_ibc",
    "dep:astroport",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
    "dep:sdk",
    "dep:serde",
]
osmosis = [
    "sdk/cosmos",
    "dep:osmosis-std",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
    "dep:sdk",
    "dep:serde",
]

testing = ["finance/testing", "dep:serde", "dex/testing"]

[dependencies]
currency = { workspace = true, optional = true }
dex = { workspace = true, optional = true }
finance = { workspace = true, optional = true }
oracle = { workspace = true, optional = true, features = ["stub_swap"] }
platform = { workspace = true, optional = true }
sdk = { workspace = true, optional = true }

astroport = { workspace = true, optional = true }
osmosis-std = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
platform = { workspace = true, features = ["testing"] }

base64 = { workspace = true, features = ["alloc"] }
