lints = { workspace = true }

[package]
name = "swap"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "$dex"], always-on = ["$dex"], include-rest = false, generics = { "$dex" = "dex" } },
    { tags = ["ci", "@agnostic"], always-on = ["testing"], include-rest = false },
]
feature-groups = { dex = { members = ["dex-astroport_main", "dex-astroport_test", "dex-osmosis"], at-least-one = true, mutually-exclusive = true } }

[features]
dex-astroport_test = [
    "dep:astroport",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos_ibc",
    "dep:serde",
]
dex-astroport_main = [
    "dep:astroport",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos_ibc",
    "dep:serde",
]
dex-osmosis = [
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:osmosis-std",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos",
    "dep:serde",
]

testing = [
    "dep:currency",
    "currency/testing",
    "dep:dex",
    "dex/testing",
    "dep:finance",
    "finance/testing",
    "dep:oracle",
    "oracle/stub_swap",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos_proto",
    "dep:prost",
    "dep:serde",
]

[dependencies]
dex = { workspace = true, optional = true }
oracle = { workspace = true, optional = true }

currency = { workspace = true, optional = true }
finance = { workspace = true, optional = true }
platform = { workspace = true, optional = true }
sdk = { workspace = true, optional = true }

astroport = { workspace = true, optional = true }
osmosis-std = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
prost = { workspace = true, optional = true, features = ["derive", "std"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
dex = { workspace = true }
finance = { workspace = true }
oracle = { workspace = true }
platform = { workspace = true, features = ["testing"] }
sdk = { workspace = true }

base64 = { workspace = true, features = ["alloc"] }
prost = { workspace = true }
