[package]
name = "marketprice"
version = "0.2.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
testing = [
    "currency/testing",
    "finance/testing",
    "platform/testing",
    "swap/testing",
]

[dependencies]
currency = { workspace = true }
finance = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true, features = ["storage", "schema"] }
swap = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
postcard = { workspace = true, features = ["alloc"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
finance = { workspace = true, features = ["testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { workspace = true, features = ["testing"] }
