[package]
name = "currency"
version = "0.5.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
testing = []

[dependencies]
finance = { workspace = true }
sdk = { workspace = true, features = ["schema"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
finance = { workspace = true, features = ["testing"] }
