[package]
name = "currency"
version = "0.6.1"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
# TODO check if this feature is used only by the protocol and if yes, take it out 
# into a `currency` package at `protocol` level
impl = []          # DEX- and NET- specific Currency and Group implementations
testing = ["impl"]

[dependencies]
sdk = { workspace = true, features = ["schema"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
