name: "Build optimized"
run-name: "Building optimized version of smart contracts"

on:
  workflow_call:

jobs:
  generate_release_version:
    runs-on: "ubuntu-latest"
    outputs:
      release_version: "${{ steps.release_version.outputs.release_version }}"
    steps:
      - id: "release_version"
        shell: "sh"
        run: |
          release_version="${{ github.ref_name }}-$(date -Iminute)"

          echo "release_version=${release_version}" >> "$GITHUB_OUTPUT"

          echo "Release version: ${release_version}" >> "${GITHUB_STEP_SUMMARY}"
  build_optimized_contracts:
    runs-on: "ubuntu-latest"
    needs: "generate_release_version"
    strategy:
      fail-fast: false
      matrix:
        working_directory: ["protocol"]
        net: ["dev", "test", "main"]
        protocol: ["osmosis", "astroport"]
        include:
          - working_directory: "platform"
    name: "Building contracts [${{ matrix.working_directory }}; ${{ matrix.net }}; ${{ matrix.protocol }}]"
    steps:
      - uses: "actions/checkout@v4.1.1"
      - name: "Build optimized binaries of platform contracts"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: ${{ matrix.net }}
          target_protocol: "${{ matrix.protocol }}"
          release_version: "${{ needs.generate_release_version.outputs.release_version }}"
          working_directory: "${{ matrix.working_directory }}"
