name: "Build optimized protocol contracts"
run-name: 'Building optimized version of "protocol" smart contracts'

on:
  workflow_call:
    inputs:
      target_dex:
        type: string
        required: true
      release_version:
        type: "string"
        required: true

jobs:
  build_optimized_protocol_contracts_dev:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries of protocol contracts"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "dev"
          target_dex: "${{ inputs.target_dex }}"
          release_version: "${{ inputs.release_version }}"
          working_directory: "protocol"
  build_optimized_protocol_contracts_test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries of protocol contracts"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "test"
          target_dex: "${{ inputs.target_dex }}"
          release_version: "${{ inputs.release_version }}"
          working_directory: "protocol"
  build_optimized_protocol_contracts_main:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries of protocol contracts"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "main"
          target_dex: "${{ inputs.target_dex }}"
          release_version: "${{ inputs.release_version }}"
          working_directory: "protocol"
