name: "Smart Contracts"
run-name: "Running checks on smart contracts"

on:
  workflow_call:

jobs:
  perform_checks:
    uses: "./.github/workflows/checks.yaml"
    strategy:
      fail-fast: false
      matrix:
        working_directory: [ "protocol" ]
        net: [ "dev", "test", "main" ]
        protocol: [ "osmosis-osmosis-usdc_axelar", "osmosis-osmosis-usdc_noble" ] # TODO Add `astroport`
        include:
          - working_directory: "platform"
          - protocol: "osmosis-osmosis-usdc_axelar"
            working_directory: "tests"
          - protocol: "osmosis-osmosis-usdc_nobler"
            working_directory: "tests"
          # - protocol: "astroport" # TODO Add `astroport`
          #   working_directory: "tests"
          - working_directory: "tools"
    name: "Checks [${{ matrix.working_directory }}; ${{ matrix.net }}; ${{ matrix.protocol }}]"
    with:
      target_net: "${{ matrix.net }}"
      target_protocol: "${{ matrix.protocol }}"
      protocols_list: "astroport,osmosis-osmosis-usdc_axelar,osmosis-osmosis-usdc_noble"
      working_directory: "${{ matrix.working_directory }}"
