name: "Code coverage"
run-name: "Running code coverage for smart contracts"

on:
  workflow_call:
    inputs:
      target_net:
        required: false
        type: "string"
      target_protocol:
        required: false
        type: "string"
      working_directory:
        required: true
        type: "string"

env:
  CARGO_TERM_COLOR: "always"
  # Release version is set to `ci` to allow building during checking and testing
  # pipelines, which is ignored during optimized builds.
  RELEASE_VERSION: "ci"

jobs:
  setup_env:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.1"
      - uses: "./.github/actions/env"
        with:
          target_net: "${{ inputs.target_net }}"
          target_protocol: "${{ inputs.target_protocol }}"
  code_coverage:
    runs-on: "ubuntu-latest"
    needs: "setup_env"
    steps:
      - uses: "actions/checkout@v4.1.1"
      - uses: "nolus-protocol/rust-ci-actions/rust_cache@main"
      - uses: "nolus-protocol/rust-ci-actions/code_coverage@main"
        with:
          features: "${{ env.FEATURES }}"
          working_directory: "${{ inputs.working_directory }}"
