name: "Code coverage"
run-name: "Running code coverage for smart contracts"

on:
  workflow_call:
    inputs:
      target_dex:
        required: false
        type: "string"
      working_directory:
        required: true
        type: "string"

env:
  CARGO_TERM_COLOR: "always"
  # Release version is set to `ci` to allow building during checking and testing
  # pipelines, which is ignored during optimized builds.
  RELEASE_VERSION: "ci"
  # Network's name is set to `main` to allow building during checking and testing
  # pipelines, which is ignored during optimized builds.
  NET: "main"
  # DEX name to check with
  DEX: "${{ inputs.target_dex }}"

jobs:
  code_coverage:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "nolus-protocol/rust-ci-actions/rust_cache@main"
      - uses: "nolus-protocol/rust-ci-actions/code_coverage@main"
        with:
          working_directory: "${{ inputs.working_directory }}"
