name: "<Callable> Run checks & build"
run-name: "Running workflow for smart contracts"

on:
  workflow_dispatch:
    inputs:
      check-dependencies-version:
        description: "Check dependencies' versions."
        required: true
        default: true
        type: "boolean"
      upload-artifacts:
        description: "Upload optimized builds as artifacts."
        required: true
        default: false
        type: "boolean"
  push:
    branches:
      - "main"
      - "KirilMihaylov/*"
    tags:
      - "*"
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"

concurrency:
  cancel-in-progress: true
  group: |-
    ${{ format('{0}-{1}-{2}-{3}', github.ref_name, github.ref_type, github.event_name, inputs.check-dependencies-version, inputs.upload-artifacts) }}

defaults:
  run:
    shell: "sh"

env:
  CARGO_TERM_COLOR: "always"
  RELEASE_VERSION: "ci"
  check-dependencies-versions: |-
    ${{ toJSON(github.ref_type == 'tag' || (github.event_name == 'workflow_dispatch' && inputs.check-dependencies-version)) }}
  upload-artifacts: |-
    ${{ toJSON(github.ref_type == 'tag' || (github.event_name == 'workflow_dispatch' && inputs.upload-artifacts)) }}

permissions:
  actions: "none"
  attestations: "none"
  checks: "none"
  contents: "read"
  deployments: "none"
  discussions: "none"
  id-token: "none"
  issues: "none"
  packages: "none"
  pages: "none"
  pull-requests: "none"
  repository-projects: "none"
  security-events: "none"
  statuses: "none"

jobs:
  load-configuration:
    runs-on: "ubuntu-24.04"
    name: "Load configuration"
    outputs:
      dex-types-json: |-
        ${{ steps.configuration.outputs.dex-types-json }}
      profiles-json: |-
        ${{ steps.configuration.outputs.profiles-json }}
      workspaces-json: |-
        ${{ steps.configuration.outputs.workspaces-json }}
    steps:
      - uses: "actions/checkout@v4"
      - id: "configuration"
        name: "Load configuration"
        run: |-
          set -eu

          . "./scripts/check/configuration.sh"

          workspaces_quoted="$(
            "jq" \
              --raw-input \
              <<EOF
          ${workspaces:?}
          EOF
          )"

          workspaces_json="$(
            "jq" \
              --slurp \
              <<EOF
          ${workspaces_quoted:?}
          EOF
          )"

          dex_types_quoted="$(
            "jq" \
              --raw-input \
              <<EOF
          ${dex_types:?}
          EOF
          )"

          dex_types_json="$(
            "jq" \
              --slurp \
              <<EOF
          ${dex_types_quoted:?}
          EOF
          )"

          profiles_quoted="$(
            "jq" \
              --raw-input \
              <<EOF
          ${profiles:?}
          EOF
          )"

          profiles_json="$(
            "jq" \
              --slurp \
              <<EOF
          ${profiles_quoted:?}
          EOF
          )"

          "echo" \
            "workspaces-json<<EOF
          ${workspaces_json:?}
          EOF
          dex-types-json<<EOF
          ${dex_types_json:?}
          EOF
          profiles-json<<EOF
          ${profiles_json:?}
          EOF" \
            >>"${GITHUB_OUTPUT}"
  prepare_tool_caches:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        local:
          - "false"
        tool:
          - "cargo-audit"
          - "cargo-nextest"
          - "cargo-udeps"
          - "git-cliff"
        include:
          - local: "true"
            tool: "cargo-each"
    name: |-
      Prepare tool caches [${{ matrix.tool }}]
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: |-
          Install `${{ matrix.tool }}` and create cache
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "false"
          local: "${{ matrix.local }}"
          no-fetching: "true"
          tool: "${{ matrix.tool }}"
  check-lock-files:
    needs:
      - "load-configuration"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        workspace: "${{ fromJSON(needs.load-configuration.outputs.workspaces-json) }}"
    name: |-
      Check lock files [${{ matrix.workspace }}]
    steps:
      - uses: "actions/checkout@v4"
      - if: |-
          fromJSON(env.check-dependencies-versions)
        name: "Load configuration"
        run: |-
          "cargo" \
            "update" \
            --locked
        working-directory: |-
          ${{ matrix.workspace }}
  workspace_check:
    needs:
      - "load-configuration"
      - "prepare_tool_caches"
      - "check-lock-files"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        workspace: "${{ fromJSON(needs.load-configuration.outputs.workspaces-json) }}"
    env:
      workspace: |-
        ${{ matrix.workspace }}
    name: |-
      Workspace-level checks [${{ matrix.workspace }}]
    steps:
      - name: "Update Rust"
        run: |-
          "rustup" "update"
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Install `cargo-audit` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "false"
          no-fetching: "false"
          tool: "cargo-audit"
      - name: "Copy `.cargo` configuration"
        run: |-
          set -eu

          "cp" \
            -R \
            "./.cargo" \
            "./${workspace:?}/.cargo"
      - name: "Run workspace-level checks"
        run: |-
          set -eu

          "sh" \
            -eu \
            "./scripts/check/workspace_checks.sh" \
            "./${workspace:?}"
  instance_lint:
    needs:
      - "load-configuration"
      - "prepare_tool_caches"
      - "check-lock-files"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        dex-type: "${{ fromJSON(needs.load-configuration.outputs.dex-types-json) }}"
        profile: "${{ fromJSON(needs.load-configuration.outputs.profiles-json) }}"
        workspace: "${{ fromJSON(needs.load-configuration.outputs.workspaces-json) }}"
    name: |-
      Instance-level lints [${{ matrix.workspace }}; ${{ matrix.dex-type }}; ${{ matrix.profile }}]
    steps:
      - name: "Update Rust"
        run: |-
          "rustup" "update"
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Install `cargo-each` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "true"
          no-fetching: "false"
          tool: "cargo-each"
      - name: "Copy CI build configuration"
        run: |-
          "cp" \
            -R \
            "./.github/test-data/build-configuration" \
            "./"
      - env:
          dex_type: |-
            ${{ matrix.dex-type }}
          profile: |-
            ${{ matrix.profile }}
          RUN_CLIPPY_QUIET: "1"
          workspace: |-
            ${{ matrix.workspace }}
        name: "Run instance-level lints"
        run: |-
          set -eu

          "sh" \
            -eu \
            "./scripts/check/instance_lint.sh" \
            "./${workspace:?}" \
            "${dex_type:?}" \
            "${profile:?}"
  instance_check_deps:
    needs:
      - "load-configuration"
      - "prepare_tool_caches"
      - "check-lock-files"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        dex-type: "${{ fromJSON(needs.load-configuration.outputs.dex-types-json) }}"
        workspace: "${{ fromJSON(needs.load-configuration.outputs.workspaces-json) }}"
    name: |-
      Check instance dependencies [${{ matrix.workspace }}; ${{ matrix.dex-type }}]
    steps:
      - name: "Update Rust"
        run: |-
          "rustup" "update"
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Install `cargo-udeps` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "false"
          no-fetching: "false"
          tool: "cargo-udeps"
      - name: "Install `cargo-each` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "true"
          no-fetching: "false"
          tool: "cargo-each"
      - name: "Install nightly Rust toolchain"
        run: |-
          "rustup" \
            "toolchain" \
            "add" \
            "nightly"
      - name: "Copy CI build configuration"
        run: |-
          "cp" \
            -R \
            "./.github/test-data/build-configuration" \
            "./"
      - env:
          dex_type: |-
            ${{ matrix.dex-type }}
          workspace: |-
            ${{ matrix.workspace }}
        name: "Check dependencies"
        run: |-
          set -eu

          "sh" \
            -eu \
            "./scripts/check/protocol_check_deps.sh" \
            "./${workspace:?}" \
            "${dex_type:?}"
  instance_tests:
    needs:
      - "load-configuration"
      - "prepare_tool_caches"
      - "check-lock-files"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        dex-type: "${{ fromJSON(needs.load-configuration.outputs.dex-types-json) }}"
        profile: "${{ fromJSON(needs.load-configuration.outputs.profiles-json) }}"
        workspace: "${{ fromJSON(needs.load-configuration.outputs.workspaces-json) }}"
    name: |-
      Run instance tests [${{ matrix.workspace }}; ${{ matrix.dex-type }}; ${{ matrix.profile }}]
    steps:
      - name: "Update Rust"
        run: |-
          "rustup" "update"
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Install `cargo-each` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "true"
          no-fetching: "false"
          tool: "cargo-each"
      - name: "Install `cargo-nextest` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "false"
          no-fetching: "false"
          tool: "cargo-nextest"
      - name: "Copy CI build configuration"
        run: |-
          "cp" \
            -R \
            "./.github/test-data/build-configuration" \
            "./"
      - env:
          dex_type: |-
            ${{ matrix.dex-type }}
          profile: |-
            ${{ matrix.profile }}
          USE_NEXTEST: "1"
          workspace: |-
            ${{ matrix.workspace }}
        name: "Run instance tests"
        run: |-
          set -eu

          "sh" \
            -eu \
            "./scripts/check/instance_tests.sh" \
            "./${workspace:?}" \
            "${dex_type:?}" \
            "${profile:?}"
  build_images:
    needs:
      - "workspace_check"
      - "instance_lint"
      - "instance_check_deps"
      - "instance_tests"
    runs-on: "ubuntu-24.04"
    name: "Build platform binaries and protocol container image"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: "0"
          fetch-tags: "true"
      - id: "container-cache-epoch"
        run: |-
          set -eu

          epoch="$(
            "date" \
              -u \
              "+%W-%Y"
          )"

          "echo" \
            "epoch<<EOF
          ${epoch:?}
          EOF" \
            >>"${GITHUB_OUTPUT:?}"
      - id: "cosmwasm-check-version"
        name: "Fetch latest `cosmwasm-check` version"
        run: |-
          set -eu

          cosmwasm_check_version="$(
            CARGO_TERM_COLOR="never" \
              "cargo" \
              "info" \
              "cosmwasm-check"
          )"
          cosmwasm_check_version="$(
            "grep" \
              "^version: " \
              <<EOF
          ${cosmwasm_check_version:?}
          EOF
          )"
          cosmwasm_check_version="$(
            "tail" \
              -n "1" \
              <<EOF
          ${cosmwasm_check_version:?}
          EOF
          )"
          cosmwasm_check_version="$(
            "sed" \
              -e "s/^version: //g" \
              <<EOF
          ${cosmwasm_check_version:?}
          EOF
          )"

          "echo" \
            "cosmwasm-check-version<<EOF
          ${cosmwasm_check_version:?}
          EOF" \
            >>"${GITHUB_OUTPUT}"
      - name: "Setup Buildkit"
        uses: "docker/setup-buildx-action@v3"
        with:
          cache-binary: "true"
          cleanup: "false"
      - name: "Produce `platform-builder` image"
        uses: "docker/build-push-action@v6"
        with:
          build-args: |-
            check_dependencies_updated=${{ env.check-dependencies-versions }}
            cosmwasm_check_ver=${{ steps.cosmwasm-check-version.outputs.cosmwasm-check-version }}
          cache-from: |-
            type=gha,scope=platform-builder-${{ steps.container-cache-epoch.outputs.epoch }}
          cache-to: |-
            type=gha,scope=platform-builder-${{ steps.container-cache-epoch.outputs.epoch }},mode=max
          context: "./"
          file: "build.Containerfile"
          load: "true"
          tags: "platform-builder"
          target: "platform-builder"
      - name: "Produce `protocol-builder` image"
        uses: "docker/build-push-action@v6"
        with:
          build-args: |-
            check_dependencies_updated=${{ env.check-dependencies-versions }}
            cosmwasm_check_ver=${{ steps.cosmwasm-check-version.outputs.cosmwasm-check-version }}
          cache-from: |-
            type=gha,scope=protocol-builder-${{ steps.container-cache-epoch.outputs.epoch }}
          cache-to: |-
            type=gha,scope=protocol-builder-${{ steps.container-cache-epoch.outputs.epoch }},mode=max
          context: "./"
          file: "build.Containerfile"
          load: "true"
          tags: "protocol-builder"
          target: "protocol-builder"
      - name: "Export `platform-builder` image"
        run: |-
          set -eu

          "docker" \
            "image" \
            "save" \
            --output "platform-builder.tar" \
            "platform-builder"
      - if: |-
          fromJSON(env.upload-artifacts)
        name: "Export `protocol-builder` image"
        run: |-
          set -eu

          "docker" \
            "image" \
            "save" \
            --output "protocol-builder.tar" \
            "protocol-builder"
      - name: "Upload `platform-builder` image"
        uses: "actions/upload-artifact@v4"
        with:
          if-no-files-found: "error"
          name: "platform-builder"
          path: |-
            ./platform-builder.tar
      - if: |-
          fromJSON(env.upload-artifacts)
        name: "Upload `protocol-builder` image"
        uses: "actions/upload-artifact@v4"
        with:
          if-no-files-found: "error"
          name: "protocol-builder"
          path: |-
            ./protocol-builder.tar
  build_binaries:
    needs:
      - "build_images"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: true
      matrix:
        network-type:
          - "test-net"
          - "production-net"
    env:
      network_type: |-
        ${{ matrix.network-type }}
    name: |-
      Build ${{ matrix.network-type }} platform binaries
    steps:
      - name: "Download `platform-builder` image artifact"
        uses: "actions/download-artifact@v4"
        with:
          name: "platform-builder"
      - run: |-
          set -eu

          "docker" \
            "image" \
            "load" \
            --input "platform-builder.tar"
      - run: |-
          set -eu

          "mkdir" "./artifacts/"

          "docker" \
            "run" \
            --volume "./artifacts/:/artifacts/:rw" \
            "platform-builder" \
            "${network_type:?}"
      - if: |-
          fromJSON(env.upload-artifacts)
        name: |-
          Upload ${{ matrix.network-type }} `platform` binaries
        uses: "actions/upload-artifact@v4"
        with:
          if-no-files-found: "error"
          name: |-
            platform-${{ matrix.network-type }}
          path: |-
            ./artifacts/*
  create_draft_release:
    needs:
      - "build_images"
      - "build_binaries"
    if: |-
      github.ref_type == 'tag'
    name: "Create draft release"
    permissions:
      contents: "write"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: "0"
          fetch-tags: "true"
          sparse-checkout: |-
            .github/actions/install-tool
      - name: "Install `git-cliff` from cache"
        uses: "./.github/actions/install-tool"
        with:
          fail-on-cache-miss: "true"
          local: "false"
          no-fetching: "false"
          tool: "git-cliff"
      - name: "Download produced artifacts"
        uses: "actions/download-artifact@v4"
        with:
          merge-multiple: "false"
          path: "./artifacts/"
      - name: "Create test-net platform binaries archive"
        run: |-
          set -eu

          files="$(
            "find" \
              "." \
              "!" \
              -path "./**/**"
          )"

          "xargs" \
            -E "" \
            -n "1" \
            "tar" \
            -r \
            -f "../platform-test-net.tar" \
            <<EOF
          ${files:?}
          EOF
        working-directory: "./artifacts/platform-test-net/"
      - name: "Compress test-net platform binaries archive"
        run: |-
          "gzip" "./platform-test-net.tar"
        working-directory: "./artifacts/"
      - name: "Create production-net platform binaries archive"
        run: |-
          set -eu

          files="$(
            "find" \
              "." \
              "!" \
              "(" \
              -path "." \
              -o \
              -path "./**/**" \
              ")"
          )"
          files="$(
            "sed" \
              -e "s/^\\.\\/\\(.\\+\\)$/\\1/g" \
              <<EOF
          ${files:?}
          EOF
          )"
          readonly files

          "xargs" \
            -E "" \
            -n "1" \
            "tar" \
            -r \
            -f "../platform-production-net.tar" \
            <<EOF
          ${files:?}
          EOF
        working-directory: "./artifacts/platform-production-net/"
      - name: "Compress production-net platform binaries archive"
        run: |-
          "gzip" "./platform-production-net.tar"
        working-directory: "./artifacts/"
      - name: "Compress protocol builder image"
        run: |-
          set -eu

          "gzip" "./protocol-builder.tar"

          "mv" \
            "./protocol-builder.tar.gz" \
            "../"
        working-directory: "./artifacts/protocol-builder/"
      - name: "Generate changelog"
        run: |-
          "git" \
            "cliff" \
            --current \
            >"./changelog"
      - name: "Create draft release"
        uses: "softprops/action-gh-release@v2"
        with:
          name: |-
            ${{ github.ref_name }}
          draft: true
          body_path: "./changelog"
          generate_release_notes: false
          files: |
            ./artifacts/*.tar.gz
