name: "Manual Workflow"
run-name: "Manually running workflow for smart contracts"

on:
  workflow_dispatch:
    inputs:
      perform_checks:
        description: "Perform checks."
        type: "boolean"
        required: true
        default: true
      build_and_check_optimized:
        description: "Build and check optimized binaries."
        type: "boolean"
        required: true
        default: true

jobs:
  perform_checks:
    uses: "./.github/workflows/checks_general.yaml"
    if: "fromJSON(inputs.perform_checks)"
  build_and_check_optimized:
    uses: "./.github/workflows/build_and_check_optimized.yaml"
    if: "fromJSON(inputs.build_and_check_optimized)"
    with:
      upload_artifacts: false
